global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'conduit-scraper'
    metrics_path: '/actuator/prometheus'
    # host.docker.internal is a special DNS name that
    # allows Docker containers to communicate with services
    # running on the host machine.
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'conduit'
