global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'conduit-nls-server-scraper'
    metrics_path: '/actuator/prometheus'
    # host.docker.internal is a special DNS name that
    # allows Docker containers to communicate with services
    # running on the host machine.
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'nls-server'
  - job_name: 'conduit-nls-client-scraper'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'nls-client'
