global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'conduit-nls-server-scraper'
    metrics_path: '/actuator/prometheus'
    # host.docker.internal is a special DNS name that
    # allows Docker containers to communicate with services
    # running on the host machine.
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          application: 'nls-server'
  - job_name: 'conduit-nls-client-scraper'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'nls-client'
  - job_name: 'conduit-ls-server-scraper'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:7072' ]
        labels:
          application: 'ls-server'
  - job_name: 'conduit-ls-client-scraper'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:7071' ]
        labels:
          application: 'ls-client'
